node_id: 1
fusion_host: 127.0.0.1
fusion_port: 5005
array_mode: triangle
global_position:
- 0
- 0
- 1
triangle_positions:
- - 0.15
  - 0.0
  - 0.0
- - -0.075
  - 0.13
  - 0.0
- - -0.075
  - -0.13
  - 0.0
triangle_vectors:
- - 0.0
  - 0.0
  - 1.0
- - 0.0
  - 0.0
  - 1.0
- - 0.0
  - 0.0
  - 1.0
tetrahedron_positions:
- - 0.0
  - 0.0
  - 0.18
- - 0.0
  - 0.17
  - -0.06
- - -0.15
  - -0.09
  - -0.06
- - 0.15
  - -0.09
  - -0.06
tetrahedron_vectors:
- - 0.0
  - 0.0
  - 1.0
- - 0.0
  - 0.0
  - 1.0
- - 0.0
  - 0.0
  - 1.0
- - 0.0
  - 0.0
  - 1.0
pga_voltage: 1.024
ads_address: '0x48'
use_simulator: true
sampling:
  frame_hop_ms: 100
  window_seconds: 1.6
  block_samples: 128
  sample_rate: 860
network:
  host: 192.168.50.1
  port: 5005
  heartbeat_hz: 2.0
calibration_noise_rms:
- 0.645344
- 0.313366
- 0.09397
mic_bias_mv: null
